fixed #21
gap-packages/cryst pull request #22
Opened 2020-11-29 12:48 UTC by narc-Ontakac2

2020-12-01 21:02 UTC, fingolfin requested changes
Thanks! But this will require some changes, I am afraid.

2020-12-01 21:02 UTC, fingolfin commented on tst/testall.g
> +         testOptions := rec( compareFunction := "uptowhitespace") ) );
This is not correct, as it ignores the result of the tests; the return value of `TestDirectory` would need to be honored.

But the better approach is to only call `TestDirectory` once, but change the exclusion list passed to it. Something like this (pseudo-code):
```gap
exclude := [];
if LoadPackage( "crystcat" ) = fail then
  exclude := ["crystcat.tst"];
fi;
TestDirectory( DirectoriesPackageLibrary( "cryst", "tst" ),
   rec( exclude := exclude, ...
```
Also, please don't use double semicolons needlessly.

2020-12-03 05:42 UTC, narc-Ontakac2 commented
Done.

-- 
Papier ist gebundenes CO2. Bitte drucken Sie diese EMail aus und archivieren Sie sie.

2020-12-03 06:24 UTC, fingolfin approved these changes
LGTM, thanks! @gaehler OK to merge?

2021-05-25 08:00 UTC, merged